// src/engine/TaskScheduler.js
import { addDays, addWeeks } from 'date-fns';
import { DependencyGraph } from './DependencyGraph';

/**
 * 任务排程器 - 基于锚点日期和规则计算任务时间表
 */
export class TaskScheduler {
  constructor(anchors, rules, trackTemplates) {
    this.anchors = anchors;
    this.rules = rules;
    this.trackTemplates = trackTemplates;
    this.depGraph = new DependencyGraph(rules);
    this.tasks = [];
  }

  /**
   * 生成完整时间表
   * @returns {Task[]}
   */
  generate() {
    // 1. 构建依赖图
    this.depGraph.buildFromRules(this.anchors);

    // 2. 从模板生成基础任务
    this.generateBaseTasks();

    // 3. 应用规则调整
    this.applyRules();

    // 4. 计算具体日期
    this.calculateDates();

    return this.tasks;
  }

  /**
   * 从模板生成基础任务
   */
  generateBaseTasks() {
    let taskId = 1;

    for (const track of this.trackTemplates.tracks) {
      for (const subItem of track.subItems) {
        for (const taskName of subItem.tasks) {
          this.tasks.push({
            id: `task_${taskId++}`,
            name: taskName,
            track: track.name,
            subItem: subItem.name,
            startWeek: 0,
            endWeek: 0,
            dependencies: this.depGraph.getDependencies(taskName),
            duration: this.depGraph.getDuration(taskName),
            isAutoGenerated: true,
            isUserModified: false,
            notes: '',
          });
        }
      }
    }
  }

  /**
   * 应用规则调整任务
   */
  applyRules() {
    // 延迟规则应用
    const delayRules = this.rules.filter(r => r.type === 'delay');
    for (const rule of delayRules) {
      // 找到触发任务和结果任务，建立依赖
      const triggerTask = this.tasks.find(t => t.name === rule.trigger);
      const resultTask = this.tasks.find(t => t.name === rule.result);
      if (triggerTask && resultTask) {
        if (!resultTask.dependencies.includes(triggerTask.id)) {
          resultTask.dependencies.push(triggerTask.id);
        }
      }
    }
  }

  /**
   * 计算任务的开始和结束周
   */
  calculateDates() {
    // 简化实现：按条线并行推进
    const startDate = this.anchors.startDate;
    const filingDate = this.anchors.filingDate;
    const totalWeeks = Math.ceil((filingDate - startDate) / (7 * 24 * 60 * 60 * 1000));

    // 按条线分配时间片（简化：各条线并行，均匀分配）
    const weeksPerTrack = Math.floor(totalWeeks * 0.8); // 留出20%缓冲

    for (const track of ['业务', '法律', '财务', '综合']) {
      const trackTasks = this.tasks.filter(t => t.track === track);
      const taskCount = trackTasks.length;
      const weeksPerTask = Math.floor(weeksPerTrack / taskCount);

      let currentWeek = 1;
      for (const task of trackTasks) {
        const duration = task.duration || { normal: weeksPerTask, min: Math.floor(weeksPerTask * 0.7) };
        task.startWeek = currentWeek;
        task.endWeek = currentWeek + Math.floor(duration.normal / 7);
        currentWeek = task.endWeek + 1;
      }
    }
  }

  /**
   * 获取指定条线的任务
   * @param {string} track
   * @returns {Task[]}
   */
  getTasksByTrack(track) {
    return this.tasks.filter(t => t.track === track);
  }

  /**
   * 获取指定周的任务
   * @param {number} week
   * @returns {Task[]}
   */
  getTasksByWeek(week) {
    return this.tasks.filter(t => t.startWeek <= week && t.endWeek >= week);
  }
}