// src/utils/dataModels.js

/**
 * @typedef {Object} AnchorDates
 * @property {Date} startDate - 项目启动时间
 * @property {Date} baseDate - 项目申报基准日
 * @property {Date} filingDate - 项目申报时间 (A1)
 */

/**
 * @typedef {Object} Task
 * @property {string} id
 * @property {string} name
 * @property {string} track - 业务|法律|财务|综合
 * @property {string} subItem - 子事项名称
 * @property {number} startWeek - 开始周 (W1 = 第1周)
 * @property {number} endWeek - 结束周
 * @property {string[]} dependencies - 依赖的任务ID列表
 * @property {boolean} isAutoGenerated
 * @property {boolean} isUserModified
 * @property {string} notes
 */

/**
 * @typedef {Object} Rule
 * @property {string} id
 * @property {'delay'|'duration'|'sequence'|'conditional_constraint'} type
 * @property {'hard_rule'|'business_rule'} category
 * @property {string} name
 * @property {string} description
 * @property {string[]} applicableTracks
 * @property {string[]} tags
 * @property {boolean} enabled
 */

/**
 * @typedef {Object} DelayRule extends Rule
 * @property {string} trigger - 触发事件名称
 * @property {number} delayMonths - 延迟月数
 * @property {string} result - 结果事件名称
 */

/**
 * @typedef {Object} DurationRule extends Rule
 * @property {string} taskName - 任务名称
 * @property {string} subItem - 子事项名称
 * @property {number} normalDays - 正常所需天数
 * @property {number} minDays - 最短天数
 */

/**
 * @typedef {Object} SequenceRule extends Rule
 * @property {string} predecessor - 前置任务名称
 * @property {string} successor - 后继任务名称
 */

/**
 * @typedef {Object} ConditionalConstraintRule extends Rule
 * @property {{ field: string, month: number }} condition
 * @property {{ field: string, allowedRange: { start: string, end: string } }} constraint
 */

/**
 * @typedef {Object} SubItem
 * @property {string} name
 * @property {string} track
 * @property {string[]} tasks
 */

/**
 * @typedef {Object} Track
 * @property {string} name - 业务|法律|财务|综合
 * @property {string} color - 甘特图颜色
 * @property {SubItem[]} subItems
 */

export const TRACKS = ['业务', '法律', '财务', '综合'];

export const TRACK_COLORS = {
  '业务': 'bg-blue-500',
  '法律': 'bg-green-500',
  '财务': 'bg-yellow-500',
  '综合': 'bg-purple-500',
};

export const TRACK_BG_COLORS = {
  '业务': 'bg-blue-50',
  '法律': 'bg-green-50',
  '财务': 'bg-yellow-50',
  '综合': 'bg-purple-50',
};