// src/utils/excelGenerator.js
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

const TRACK_COLORS_HEX = {
  '业务': '4472C4',
  '法律': '70AD47',
  '财务': 'FFC000',
  '综合': '7030A0',
};

/**
 * 生成 Excel 文件
 * @param {Task[]} tasks
 * @param {AnchorDates} anchors
 * @param {number} totalWeeks
 * @returns {Blob}
 */
export function generateExcel(tasks, anchors, totalWeeks) {
  const wb = XLSX.utils.book_new();

  // Sheet 1: 甘特图数据
  const ganttData = buildGanttSheet(tasks, anchors, totalWeeks);
  const ws1 = XLSX.utils.aoa_to_sheet(ganttData);
  XLSX.utils.book_append_sheet(wb, ws1, '甘特图');

  // Sheet 2: 详细任务列表
  const taskData = buildTaskListSheet(tasks);
  const ws2 = XLSX.utils.aoa_to_sheet(taskData);
  XLSX.utils.book_append_sheet(wb, ws2, '任务列表');

  // 生成文件
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([wbout], { type: 'application/octet-stream' });
}

function buildGanttSheet(tasks, anchors, totalWeeks) {
  const data = [];

  // 标题行
  data.push(['IPO项目时间表']);
  data.push([
    '条线', '子事项', '任务',
    ...Array.from({ length: totalWeeks }, (_, i) => `W${i + 1}`)
  ]);

  // 按条线和子事项分组
  const grouped = {};
  for (const task of tasks) {
    const key = `${task.track}|${task.subItem}`;
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push(task);
  }

  // 数据行
  for (const [key, groupTasks] of Object.entries(grouped)) {
    const [track, subItem] = key.split('|');
    for (const task of groupTasks) {
      const row = [track, subItem, task.name];
      for (let w = 1; w <= totalWeeks; w++) {
        if (task.startWeek <= w && task.endWeek >= w) {
          row.push('█');
        } else {
          row.push('');
        }
      }
      data.push(row);
    }
  }

  return data;
}

function buildTaskListSheet(tasks) {
  const data = [
    ['任务名称', '条线', '子事项', '开始周', '结束周', '持续周数', '是否自动生成', '备注']
  ];

  for (const task of tasks) {
    data.push([
      task.name,
      task.track,
      task.subItem,
      `W${task.startWeek}`,
      `W${task.endWeek}`,
      task.endWeek - task.startWeek + 1,
      task.isAutoGenerated ? '是' : '否',
      task.notes || ''
    ]);
  }

  return data;
}

/**
 * 触发下载
 * @param {Blob} blob
 * @param {string} filename
 */
export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}