// src/App.jsx
import React, { useState, useMemo, useEffect } from 'react';
import { AnchorInput } from './components/AnchorInput';
import { GanttChart } from './components/GanttChart';
import { TaskTable } from './components/TaskTable';
import { ExcelExport } from './components/ExcelExport';
import { RuleEditor } from './components/RuleEditor/RuleEditor';
import { TaskScheduler } from './engine/TaskScheduler';
import { differenceInDays, addWeeks } from 'date-fns';

// 导入静态数据
import defaultRules from './data/defaultRules.json';
import businessRulesData from './data/businessRules.json';
import trackTemplates from './data/trackTemplates.json';

const BUSINESS_RULES_KEY = 'ipo_timeline_business_rules';

function App() {
  const [tasks, setTasks] = useState([]);
  const [anchors, setAnchors] = useState(null);
  const [totalWeeks, setTotalWeeks] = useState(0);
  const [businessRules, setBusinessRules] = useState(() => {
    // 尝试从 LocalStorage 加载
    const saved = localStorage.getItem(BUSINESS_RULES_KEY);
    return saved ? JSON.parse(saved) : businessRulesData;
  });

  // 保存业务规则到 LocalStorage
  useEffect(() => {
    localStorage.setItem(BUSINESS_RULES_KEY, JSON.stringify(businessRules));
  }, [businessRules]);

  const allRules = useMemo(() => [...defaultRules, ...businessRules], [businessRules]);

  const handleGenerate = (newAnchors) => {
    setAnchors(newAnchors);

    // 计算总周数
    const weeks = Math.ceil(
      differenceInDays(newAnchors.filingDate, newAnchors.startDate) / 7
    );
    setTotalWeeks(weeks);

    // 生成任务
    const scheduler = new TaskScheduler(newAnchors, allRules, trackTemplates);
    const generatedTasks = scheduler.generate();
    setTasks(generatedTasks);
  };

  const handleUpdateTask = (updatedTask) => {
    setTasks(tasks.map(t => t.id === updatedTask.id ? updatedTask : t));
  };

  const handleDeleteTask = (taskId) => {
    setTasks(tasks.filter(t => t.id !== taskId));
  };

  const handleAddTask = () => {
    const newTask = {
      id: `task_custom_${Date.now()}`,
      name: '新任务',
      track: '业务',
      subItem: '其他',
      startWeek: 1,
      endWeek: 2,
      dependencies: [],
      duration: { normal: 7, min: 5 },
      isAutoGenerated: false,
      isUserModified: false,
      notes: '',
    };
    setTasks([...tasks, newTask]);
  };

  const handleBusinessRulesChange = (newRules) => {
    setBusinessRules(newRules);
  };

  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <h1 className="text-2xl font-bold text-gray-900">IPO 时间表自动生成工具</h1>
          <RuleEditor
            defaultRules={defaultRules}
            businessRules={businessRules}
            onBusinessRulesChange={handleBusinessRulesChange}
          />
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-6 space-y-6">
        <AnchorInput onGenerate={handleGenerate} />

        {tasks.length > 0 && anchors && (
          <>
            <div className="flex justify-end">
              <ExcelExport tasks={tasks} anchors={anchors} totalWeeks={totalWeeks} />
            </div>

            <GanttChart
              tasks={tasks}
              startDate={anchors.startDate}
              totalWeeks={totalWeeks}
            />

            <TaskTable
              tasks={tasks}
              onUpdateTask={handleUpdateTask}
              onDeleteTask={handleDeleteTask}
              onAddTask={handleAddTask}
            />
          </>
        )}

        {tasks.length === 0 && (
          <div className="text-center py-12 text-gray-500">
            请输入项目锚点信息，点击"生成时间表"开始
          </div>
        )}
      </main>
    </div>
  );
}

export default App;